name: Build Typst document
on: push

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            agth.typ
            alg3.typ
            algo.typ
            calc2.typ
            toc.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
          agth.pdf
          alg3.pdf
          algo.pdf
          toc.pdf

